# Notebook 18: Eigenvalues, Eigenvectors and Dimension Reduction Lite
***

In this notebook, we will practice using our generalized power iteration algorithm to find all eigenvalues and eigenvectors associated with a matrix, and explore spectral dimension reduction methods.

We'll need numpy for this notebook, so let's load it.

In [1]:
import numpy as np

<br>

### Exercise 1: We want eigenvalues!

We just constructed the matrix $A_2 = A - \lambda_1 \vec{v}_1 \vec{v}_1^T = \begin{bmatrix} 8/5 & -4/5 \\ -4/5 & 2/5 \end{bmatrix}$, whose principal eigenvalue corresponds to the second eigenvalue of the original $A$ matrix. 

In [2]:
A2 = np.array([[8/5, -4/5],
               [-4/5, 2/5]])

Now we need to solve for its principal eigenpair using power iteration. This is old hat for us by now, so let's initialize our estimate for $\vec{v}_2$ as $\begin{bmatrix} 1/\sqrt{2} \\ 1/\sqrt{2} \end{bmatrix}$ and just do a quick 20 iterations:

In [3]:
v2_old = np.ones(2)/np.sqrt(2)

for k in range(20):
    v2_new = np.matmul(A2, v2_old)
    v2_old = v2_new.copy()/np.linalg.norm(v2_new)
    
v2 = v2_old
print(v2)

[ 0.89442719 -0.4472136 ]


So our estimate is $\vec{v}_2 = \begin{bmatrix} 0.89 \\ -0.45 \end{bmatrix}$. What is the estimate of the associated eigenvalue $\lambda_2$?  Check your estimate by using `np.linalg.eig` on the original matrix $A$.

In [4]:
A = np.array([[3, 2], [2, 6]])

**Solution:**

$A_2 \vec{v}_2 \stackrel{\heartsuit}{=} \lambda_2 \vec{v}_2$, so we can match components to find that $\lambda_2$ must satisfy both of the following equations:
1. $[A_2 \vec{v}_2]_1/v_{2,1} = \lambda$
1. $[A_2 \vec{v}_2]_2/v_{2,2} = \lambda$

In [5]:
# SOLUTION:

np.matmul(A2, v2)/v2

array([2., 2.])

So, it looks like the second eigenvalue is $\lambda_2= 2$. We check using numpy:

In [6]:
np.linalg.eig(A)

(array([2., 7.]), array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

<br>

### Exercise 2: Making sure we don't break Math

In lecture, we made the claim that $\vec{v}_1 = \begin{bmatrix} 1/\sqrt{5} \\ 2/\sqrt{5} \end{bmatrix}$ would be an eigenvector of $A_2$ and its corresponding eigenvalue is 0. Verify this claim for the matrix $A_2$.

In [7]:
# SOLUTION:

evals, evecs = np.linalg.eig(A2)
print(evals)
print(evecs[:,1]*np.sqrt(5))

[2. 0.]
[1. 2.]


<br>

### Exercise 3: Computing *even more* eigenstuff!

Consider the matrix $A$ given below. Finish off the code for the generalized power iteration in order to compute the eigenvalues and eigenvectors associated with $A$. Feel free to check your work using numpy and note that [numpy.outer()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html) might be a useful function for computing the outer product of two column vectors, $\vec{x}\ \vec{y}^T$.

$$A = \begin{bmatrix} 4 & 2 & 2 & 3 \\
                      2 & 4 & 1 & 2 \\
                      2 & 1 & 2 & 1 \\
                      3 & 2 & 1 & 3 \end{bmatrix}$$

In [8]:
A = np.array([[4, 2, 2, 3],
              [2, 4, 1, 2],
              [2, 1, 2, 1],
              [3, 2, 1, 3]])

In [9]:
# dimension of A
n = A.shape[0]

# lists to store the estimated eigenvalues and vectors
vals, vecs = [], []

# loop over each eigenpair to find
Ak = A.copy()
for k in range(n):
    # initialize eigenvector estimate
    v_old = np.ones(n)/np.sqrt(n)
    # 20 powerful iterations
    for _ in range(20):
        # update
        v_new = 0 # TODO!
        # normalize to have magnitude of 1
        v_new = 0 # TODO!
        # update v_old <-- v_new
        v_old = 0 # TODO!
    # solve for the eigenvalue and save
    vals.append(0) # TODO!
    # save eigenvector
    vecs.append(v_old)
    # continue with Ak by subtracting the eigenpair you just solved for
    Ak = Ak - 0 # TODO!

evals, evecs = np.linalg.eig(A)

# report the results
print("my evals = ",np.round(vals,4))
print("np evals = ",np.round(evals,4))
print()
print("my evecs = \n", np.round(vecs,4))
print("np evecs = \n", np.round(evecs,4))

my evals =  [0 0 0 0]
np evals =  [9.1488 0.175  2.3442 1.332 ]

my evecs = 
 [0 0 0 0]
np evecs = 
 [[ 0.6182  0.6586 -0.4244  0.062 ]
 [ 0.5019  0.0869  0.8361 -0.2036]
 [ 0.3154 -0.4373 -0.3323 -0.7739]
 [ 0.5162 -0.6062 -0.1016  0.5965]]


In [13]:
# SOLUTION:

# dimension of A
n = A.shape[0]

# lists to store the estimated eigenvalues and vectors
vals, vecs = [], []

# loop over each eigenpair to find
Ak = A.copy()
for k in range(n):
    # initialize eigenvector estimate
    v_old = np.ones(n)/np.sqrt(n)
    # power iteration
    for _ in range(20):
        # update
        v_new = np.matmul(Ak, v_old)
        # normalize
        v_old = v_new/np.linalg.norm(v_new)
    # solve for the eigenvalue and save
    vals.append(np.mean(np.matmul(Ak, v_old)/v_old))
    # save eigenvector
    vecs.append(v_old)
    # continue with Ak by subtracting the eigenpair you just solved for
    Ak = Ak - vals[-1]*np.outer(vecs[-1], vecs[-1])

evals, evecs = np.linalg.eig(A)

# report the results
print("my evals = ",np.round(vals,4))
print("np evals = ",np.round(evals,4))
print()
print("my evecs = \n", np.round(vecs,4))
print("np evecs = \n", np.round(evecs,4))

#Oops, we're transposed!

print("my fixed evecs = \n", np.transpose(np.round(vecs,4)))


my evals =  [9.1488 2.3444 1.332  0.175 ]
np evals =  [9.1488 0.175  2.3442 1.332 ]

my evecs = 
 [[ 0.6182  0.5019  0.3154  0.5162]
 [ 0.4244 -0.8361  0.3324  0.1015]
 [-0.0622  0.2038  0.7738 -0.5965]
 [-0.6586 -0.0869  0.4373  0.6062]]
np evecs = 
 [[ 0.6182  0.6586 -0.4244  0.062 ]
 [ 0.5019  0.0869  0.8361 -0.2036]
 [ 0.3154 -0.4373 -0.3323 -0.7739]
 [ 0.5162 -0.6062 -0.1016  0.5965]]
my fixed evecs = 
 [[ 0.6182  0.4244 -0.0622 -0.6586]
 [ 0.5019 -0.8361  0.2038 -0.0869]
 [ 0.3154  0.3324  0.7738  0.4373]
 [ 0.5162  0.1015 -0.5965  0.6062]]
